---
- name: Create CoreDNS Systemd Unit file
  template:
    src: coredns.service.j2
    dest: /lib/systemd/system/coredns.service
    mode: 0644
  register: coredns_systemd

- name: Ensure systemd-resolved stopped
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: Drop CoreDNS configuration file
  template:
    src: Corefile.j2
    dest: "{{ coredns_config_file_path }}"
    owner: "{{ coredns_user }}"
    group: "{{ coredns_group }}"
    mode: 0644
  notify: Restart CoreDNS

- name: Ensure CoreDNS started and enabled
  systemd:
    name: coredns
    state: started
    enabled: yes
    daemon_reload: yes